name: Go build

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: install and pre build
      run: go build
      
    - name: Build amd64
      run: CGO_ENABLE=0 GOOS=linux GOARCH=amd64 go build -o go-touch-mapper_amd64
    
    - name: Build arm64
      run: CGO_ENABLE=0 GOOS=linux GOARCH=arm64 go build -o go-touch-mapper_arm64
    
    - name: list
      run: ls -al
      
    - name: test help
      run: ./go-touch-mapper_amd64 -h

